version: 2
jobs:
  build:

    working_directory: ~/circle-ci-github-release

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - run: mvn verify

      - run:
          name: Store test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - store_artifacts:
          path: ./target/*.jar