version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: |
          if [[ "$CIRCLE_TAG" != "" ]]; then
            VERSION="$(echo "$CIRCLE_TAG" | grep -Po '\d+\.\d+\.\d+')"
            ./mvnw versions:set -DnewVersion=${VERSION} versions:commit
          fi
      - run: ./mvnw verify
      - persist_to_workspace:
          root: target
          paths:
            - circle-ci-github-release.jar
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  publish-github-release:
      docker:
        - image: circleci/golang:1.8
      steps:
        - checkout
        - attach_workspace:
            at: ./target
        - run:
            name: "Publish Release on GitHub"
            command: |
              go get github.com/tcnksm/ghr
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./target/
        - run:
            name: "Send Notification"
            command: ./scripts/telegram_notification.sh "success"
            when: on_success
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

