version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./mvnw verify -DskipTests=true
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: ./mvnw verify
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
